### PR TITLE
FIx ISSUE #2

### PR DESCRIPTION
**Pull request by d0dg3r**
Fixed the issue #2. I complied it and installed it on my Pixel9 Pro XL and it is running fine.

### CODE REVIEW

**Comment by Dacid99** [comment]
Hey, thanks for taking care of this problem!

Is there a reason why you set the jvm flags?
Could you maybe create this pull request on gitlab as well? This github repo is just a mirror.

**Comment by d0dg3r** [comment]
> Hey, thanks for taking care of this problem!
> 
> Is there a reason why you set the jvm flags? Could you maybe create this pull request on gitlab as well? This github repo is just a mirror.

Since you're using Java 21, those --add-opens flags are necessary because Android Gradle Plugin (AGP) needs access to some internal Java modules that are restricted by default in newer Java versions. These flags explicitly grant that access.

**Comment by d0dg3r** [comment]
But there is an issue with the layout, i have also a other fix or redesign done. 
I will have a look on the gitlab repo. 
Have a look -> https://cloud.root-files.net/s/g6cdCxYSNABzMF9
Should i push this too?

**Comment by Dacid99** [comment]
The UI change was overdue, thanks for doing that as well! It looks really good!

it would be best if you could push the ui overhaul separately, that makes it easier for me to get an overview of the individual changes.

**Comment by Dacid99** [comment]
> But there is an issue with the layout, i have also a other fix or redesign done. Have a look -> https://cloud.root-files.net/s/g6cdCxYSNABzMF9
> 
> Please send me the link to gitlab repo.

https://gitlab.com/Dacid99/linkdroid-for-linkwarden

**Comment by d0dg3r** [comment]
Ok the pull requests on gitlab are done.

**Comment by d0dg3r** [comment]
I think can close this here.

**Comment by Dacid99** [comment]
Perfect ill look into them later today!
Thanks again and see you on gitlab 😄

**Comment by Dacid99** [comment]
Thats very good, what have you used for translation?

**Comment by d0dg3r** [comment]
Deepl and AI . This is the reason i need to double check, but i have proper people in place.

**Comment by Dacid99** [comment]
Perfect just send me the merge request when it's complete 👍

**Pull request closed without merging**
